# Generated by Django 4.0.3 on 2022-04-09 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_remove_profile_phone_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
