# Generated by Django 4.0.3 on 2022-04-04 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_rename_contact_profile_phone_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='email',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(default='lastname', max_length=250),
            preserve_default=False,
        ),
    ]
