# Generated by Django 5.0.1 on 2024-01-31 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_added_validity_field_to_coupon_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='validity',
            field=models.BooleanField(default=True),
        ),
    ]
