# Generated by Django 5.0.1 on 2024-02-01 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_altered_validity_field_coupon_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon_applied',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
