# Generated by Django 4.0.3 on 2022-04-13 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_order_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(max_length=250)),
                ('transaction_id', models.CharField(max_length=250)),
                ('transaction_time', models.DateTimeField(auto_now_add=True)),
                ('transaction_amount', models.IntegerField(max_length=250)),
                ('business_short_code', models.CharField(max_length=250)),
                ('bill_ref_no', models.CharField(max_length=250)),
                ('invoice_number', models.CharField(max_length=250)),
                ('org_account_balance', models.DecimalField(decimal_places=2, max_digits=8)),
                ('third_party_trans_id', models.CharField(max_length=250)),
                ('msisdn', models.CharField(max_length=250)),
                ('first_name', models.CharField(max_length=250)),
            ],
        ),
    ]
