# Generated by Django 4.0.3 on 2022-04-13 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='transaction_amount',
            field=models.IntegerField(),
        ),
    ]
