# Generated by Django 4.0.3 on 2022-04-14 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_mpesacallbacks_mpesacalls_mpesapayment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mpesapayment',
            old_name='type',
            new_name='transaction_type',
        ),
    ]
