# Generated by Django 4.0.3 on 2022-04-14 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_rename_description_mpesapayment_invoice_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpesapayment',
            name='last_name',
            field=models.CharField(default='name', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mpesapayment',
            name='middle_name',
            field=models.CharField(default='name', max_length=100),
            preserve_default=False,
        ),
    ]
