# Generated by Django 4.0.3 on 2022-04-14 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_mpesapayment_last_name_mpesapayment_middle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpesapayment',
            name='invoice_number',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='mpesapayment',
            name='phone_number',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='mpesapayment',
            name='reference',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='mpesapayment',
            name='transaction_time',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='mpesapayment',
            name='transaction_type',
            field=models.CharField(max_length=250),
        ),
    ]
