# Generated by Django 4.0.3 on 2022-04-26 06:10

from django.db import migrations, models
import order.models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_alter_mpesapayment_organization_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.IntegerField(default=order.models.random_string, primary_key=True, serialize=False),
        ),
    ]
