# Generated by Django 4.0.3 on 2022-04-26 06:16

from django.db import migrations, models
import order.models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_alter_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.CharField(default=order.models.random_string, max_length=100, primary_key=True, serialize=False),
        ),
    ]
