# Generated by Django 4.0.3 on 2022-04-27 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_alter_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_reference',
            field=models.CharField(default='reference', max_length=100),
            preserve_default=False,
        ),
    ]
