# Generated by Django 4.0.3 on 2022-04-27 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_order_payment_reference'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='ordered',
            new_name='paid',
        ),
    ]
