# Generated by Django 4.0.3 on 2022-07-17 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0021_order_delivery_fee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentDetail',
        ),
    ]
