# Generated by Django 5.0 on 2024-01-14 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0022_delete_paymentdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_code', models.CharField(max_length=250)),
                ('coupon_amount', models.CharField(max_length=250)),
                ('coupon_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_order', to='order.order')),
            ],
        ),
    ]
