# Generated by Django 5.0 on 2024-01-14 09:55

import order.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0024_created_coupon_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='id',
        ),
        migrations.AlterField(
            model_name='coupon',
            name='coupon_code',
            field=models.CharField(default=order.models.coupon_generator, max_length=100, primary_key=True, serialize=False),
        ),
    ]
