# Generated by Django 5.0 on 2024-01-14 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0027_added_user_field_coupon_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='coupon_amount',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
