# Generated by Django 5.0 on 2024-01-17 04:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0029_altered_field_user_on_coupon'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('receipt_no', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('received_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('payment_method', models.CharField(blank=True, choices=[('', 'Payment Method'), ('Cash', 'Cash'), ('Mpesa', 'Mpesa'), ('Cheque', 'Cheque'), ('EFT', 'EFT')], default='', max_length=250)),
                ('received_by', models.CharField(blank=True, max_length=250)),
                ('reference_no', models.CharField(blank=True, max_length=250, null=True)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=8)),
                ('receipt_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_order', to='order.order')),
                ('receipt_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
