# Generated by Django 5.0 on 2024-01-17 11:05

import order.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0030_creating_receipt_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='invoice_no',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='receipt',
            name='receipt_no',
            field=models.CharField(default=order.models.receipt_number_gen, max_length=100, primary_key=True, serialize=False),
        ),
    ]
