# Generated by Django 5.0 on 2024-01-18 05:53

import django.utils.timezone
import order.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0031_added_invoice_no_field_to_order_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='invoice_no',
            field=models.CharField(default=order.models.invoice_number_gen, max_length=250),
        ),
    ]
