# Generated by Django 5.0 on 2024-01-29 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0034_altered_coupon_user_attribute_and_its_related_naname_on_coupon_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='activation_status',
            field=models.BooleanField(default=False),
        ),
    ]
